/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;


/**
 *
 * @author ACER
 */
public class AdminProfileView extends javax.swing.JFrame {

    /**
     * Creates new form AdminProfileView
     */
    public AdminProfileView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ProfileToggleButton = new javax.swing.JToggleButton();
        MenuToggleButton = new javax.swing.JToggleButton();
        HomeToggleButton = new javax.swing.JToggleButton();
        OrderToggleButton = new javax.swing.JToggleButton();
        LogoutToggleButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        AdminNamejLabel = new javax.swing.JLabel();
        ResturantPhotojPanel = new javax.swing.JPanel();
        ResturantNameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        UpdateProfileButton = new javax.swing.JButton();
        ResturantNameTextField = new javax.swing.JTextField();
        NumberTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        ResturantAddressTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel7.setText("Sajilo Serve");

        ProfileToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        ProfileToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/Profileicon.png"))); // NOI18N
        ProfileToggleButton.setText("Profile");
        ProfileToggleButton.setBorderPainted(false);
        ProfileToggleButton.setContentAreaFilled(false);
        ProfileToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ProfileToggleButton.setMinimumSize(new java.awt.Dimension(176, 54));
        ProfileToggleButton.setPreferredSize(new java.awt.Dimension(100, 54));
        ProfileToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileToggleButtonActionPerformed(evt);
            }
        });

        MenuToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        MenuToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/menuicon.png"))); // NOI18N
        MenuToggleButton.setText("Menu");
        MenuToggleButton.setBorderPainted(false);
        MenuToggleButton.setContentAreaFilled(false);
        MenuToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MenuToggleButton.setIconTextGap(8);
        MenuToggleButton.setPreferredSize(new java.awt.Dimension(100, 54));
        MenuToggleButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuToggleButtonActionPerformed(evt);
            }
        });

        HomeToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        HomeToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/homeicone.png (1).png"))); // NOI18N
        HomeToggleButton.setText("Home");
        HomeToggleButton.setBorderPainted(false);
        HomeToggleButton.setContentAreaFilled(false);
        HomeToggleButton.setPreferredSize(new java.awt.Dimension(100, 54));
        HomeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeToggleButtonActionPerformed(evt);
            }
        });

        OrderToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        OrderToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/Ordersicon.png"))); // NOI18N
        OrderToggleButton.setText("Ordes");
        OrderToggleButton.setBorderPainted(false);
        OrderToggleButton.setContentAreaFilled(false);
        OrderToggleButton.setPreferredSize(new java.awt.Dimension(100, 54));
        OrderToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderToggleButtonActionPerformed(evt);
            }
        });

        LogoutToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        LogoutToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/logouticon.png"))); // NOI18N
        LogoutToggleButton.setText("Logout");
        LogoutToggleButton.setBorderPainted(false);
        LogoutToggleButton.setContentAreaFilled(false);
        LogoutToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LogoutToggleButton.setIconTextGap(2);
        LogoutToggleButton.setPreferredSize(new java.awt.Dimension(100, 54));
        LogoutToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProfileToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(MenuToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(84, 84, 84)
                .addComponent(HomeToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84)
                .addComponent(ProfileToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(MenuToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(84, 84, 84)
                .addComponent(OrderToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(84, 84, 84)
                .addComponent(LogoutToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 840));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        jLabel1.setText("Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel1)
                .addGap(570, 570, 570))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1310, 120));

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminNamejLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        AdminNamejLabel.setText("Admin's Name");
        jPanel4.add(AdminNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        javax.swing.GroupLayout ResturantPhotojPanelLayout = new javax.swing.GroupLayout(ResturantPhotojPanel);
        ResturantPhotojPanel.setLayout(ResturantPhotojPanelLayout);
        ResturantPhotojPanelLayout.setHorizontalGroup(
            ResturantPhotojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        ResturantPhotojPanelLayout.setVerticalGroup(
            ResturantPhotojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        jPanel4.add(ResturantPhotojPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 287, 340, -1));

        ResturantNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        ResturantNameLabel.setText("Resturant's Name");
        jPanel4.add(ResturantNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 260, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 258, 410, 10));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Resturant Name:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 152, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Phone Number:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 244, 189, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Email Address:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 336, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Resturant address:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 428, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Name:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 60, -1, -1));
        jPanel5.add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 62, 470, 30));

        UpdateProfileButton.setBackground(new java.awt.Color(255, 153, 51));
        UpdateProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateProfileButton.setText("Update Profile");
        UpdateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProfileButtonActionPerformed(evt);
            }
        });
        jPanel5.add(UpdateProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 529, -1, 50));

        ResturantNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResturantNameTextFieldActionPerformed(evt);
            }
        });
        jPanel5.add(ResturantNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 154, 370, 30));
        jPanel5.add(NumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 246, 370, 30));
        jPanel5.add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 338, 380, 30));
        jPanel5.add(ResturantAddressTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 430, 350, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 1300, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileButtonActionPerformed

    private void ProfileToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileToggleButtonActionPerformed

    private void HomeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeToggleButtonActionPerformed

    private void OrderToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderToggleButtonActionPerformed

    private void LogoutToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutToggleButtonActionPerformed

    private void MenuToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuToggleButtonActionPerformed

    private void ResturantNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResturantNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResturantNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminProfileView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminNamejLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JToggleButton HomeToggleButton;
    private javax.swing.JToggleButton LogoutToggleButton;
    private javax.swing.JToggleButton MenuToggleButton;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField NumberTextField;
    private javax.swing.JToggleButton OrderToggleButton;
    private javax.swing.JToggleButton ProfileToggleButton;
    private javax.swing.JTextField ResturantAddressTextField6;
    private javax.swing.JLabel ResturantNameLabel;
    private javax.swing.JTextField ResturantNameTextField;
    private javax.swing.JPanel ResturantPhotojPanel;
    private javax.swing.JButton UpdateProfileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables


}
