/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.Image;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import restaurant.management.system.UIElements.CustomButton;
import restaurant.management.system.UIElements.PanelRound;
import restaurant.management.system.UIElements.PasswordField;
import restaurant.management.system.UIElements.RoundedTextField;

/**
 *
 * @author samee
 */
public class AdminAccountManagementView extends javax.swing.JFrame {

    /**
     * Creates new form AdminChangePasswordView
     */
    public AdminAccountManagementView() {
        initComponents();
        scaleImage1();
        scaleImage2();
        scaleImage3();
        scaleImage4();
        scaleImage5();
        scaleImage6();
        changeUsernamePanelRound.setVisible(false);
        changePasswordPanelRound.setVisible(false);
        deleteAccountPanelRound.setVisible(false);
        changeUsernamePanelRound.add(changePasswordPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 780, 540));
        jPanel1.add(changePasswordPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 780, 540));
        jPanel1.add(deleteAccountPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 780, 540));
    }
    
    public void scaleImage1(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/ImagePicker/home.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(homeIcon.getWidth(), homeIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        homeIcon.setIcon(scaledIcon);
    }
    
    public void scaleImage2(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/ImagePicker/user.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(profileIcon.getWidth(), profileIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        profileIcon.setIcon(scaledIcon);
    }
    
    public void scaleImage3(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/ImagePicker/menu.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(menuIcon.getWidth(), menuIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        menuIcon.setIcon(scaledIcon);
    }
    
    public void scaleImage4(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/ImagePicker/check.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(orderIcon.getWidth(), orderIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        orderIcon.setIcon(scaledIcon);
    }
    
    public void scaleImage5(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/ImagePicker/logout.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(logoutIcon.getWidth(), logoutIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        logoutIcon.setIcon(scaledIcon); // Centers it on screen (optional)
    }
    
    public void scaleImage6(){
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/ImagePicker/Logo.png"));
        //scaling image to fit in the hlabel.
        Image img1 = icon1.getImage();
        Image imgScale = img1.getScaledInstance(logoIcon.getWidth(), logoIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        logoIcon.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new restaurant.management.system.UIElements.PanelRound();
        deleteAccountButton = new restaurant.management.system.UIElements.CustomButton();
        changePasswordButton = new restaurant.management.system.UIElements.CustomButton();
        changeUsernameButton = new restaurant.management.system.UIElements.CustomButton();
        changeUsernamePanelRound = new restaurant.management.system.UIElements.PanelRound();
        changePasswordPanelRound = new restaurant.management.system.UIElements.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        confirmNewPasswordTextField = new restaurant.management.system.UIElements.PasswordField();
        changeButton1 = new restaurant.management.system.UIElements.CustomButton();
        currentPasswordTextField = new restaurant.management.system.UIElements.PasswordField();
        newPasswordTextField2 = new restaurant.management.system.UIElements.PasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newUsernameTextField = new restaurant.management.system.UIElements.RoundedTextField();
        passwordTextField = new restaurant.management.system.UIElements.PasswordField();
        currentUsernameTextField = new restaurant.management.system.UIElements.RoundedTextField();
        changeButton = new restaurant.management.system.UIElements.CustomButton();
        deleteAccountPanelRound = new restaurant.management.system.UIElements.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deletePasswordTextField = new restaurant.management.system.UIElements.PasswordField();
        deleteConfirmPasswordTextField = new restaurant.management.system.UIElements.PasswordField();
        deleteAccountConfirmButton = new restaurant.management.system.UIElements.CustomButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        logoutlabel = new javax.swing.JLabel();
        homelabel = new javax.swing.JLabel();
        profilelabel = new javax.swing.JLabel();
        menulabel = new javax.swing.JLabel();
        orderlabel = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        profileIcon = new javax.swing.JLabel();
        menuIcon = new javax.swing.JLabel();
        orderIcon = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 204, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setRoundBottonLeft(100);
        panelRound1.setRoundBottonRight(100);
        panelRound1.setRoundTopLeft(100);
        panelRound1.setRoundTopRight(100);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteAccountButton.setBackground(new java.awt.Color(239, 167, 9));
        deleteAccountButton.setBorder(null);
        deleteAccountButton.setText("Delete Account");
        deleteAccountButton.setBorderColor(new java.awt.Color(239, 167, 9));
        deleteAccountButton.setFocusable(false);
        deleteAccountButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        deleteAccountButton.setRadius(50);
        panelRound1.add(deleteAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 380, 50));

        changePasswordButton.setBackground(new java.awt.Color(239, 167, 9));
        changePasswordButton.setBorder(null);
        changePasswordButton.setText("Change Password");
        changePasswordButton.setBorderColor(new java.awt.Color(239, 167, 9));
        changePasswordButton.setFocusable(false);
        changePasswordButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        changePasswordButton.setRadius(50);
        panelRound1.add(changePasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 380, 50));

        changeUsernameButton.setBackground(new java.awt.Color(239, 167, 9));
        changeUsernameButton.setBorder(null);
        changeUsernameButton.setText("Change Username");
        changeUsernameButton.setBorderColor(new java.awt.Color(239, 167, 9));
        changeUsernameButton.setFocusable(false);
        changeUsernameButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        changeUsernameButton.setRadius(50);
        changeUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernameButtonActionPerformed(evt);
            }
        });
        panelRound1.add(changeUsernameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 380, 50));

        jPanel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 470, 350));

        changeUsernamePanelRound.setRoundBottonLeft(100);
        changeUsernamePanelRound.setRoundBottonRight(100);
        changeUsernamePanelRound.setRoundTopLeft(100);
        changeUsernamePanelRound.setRoundTopRight(100);
        changeUsernamePanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changePasswordPanelRound.setRoundBottonLeft(100);
        changePasswordPanelRound.setRoundBottonRight(100);
        changePasswordPanelRound.setRoundTopLeft(100);
        changePasswordPanelRound.setRoundTopRight(100);
        changePasswordPanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel11.setText("Confirm New Password:");
        changePasswordPanelRound.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 257, 25));

        jLabel12.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel12.setText("New Password:");
        changePasswordPanelRound.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 257, 25));

        jLabel13.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel13.setText("Current Password:");
        changePasswordPanelRound.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 240, 25));
        changePasswordPanelRound.add(confirmNewPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 700, 50));

        changeButton1.setBackground(new java.awt.Color(239, 167, 9));
        changeButton1.setBorder(null);
        changeButton1.setText("Change ");
        changeButton1.setBorderColor(new java.awt.Color(239, 167, 9));
        changeButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        changeButton1.setRadius(50);
        changePasswordPanelRound.add(changeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 300, 50));

        currentPasswordTextField.setFont(new java.awt.Font("Mongolian Baiti", 0, 20)); // NOI18N
        changePasswordPanelRound.add(currentPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 700, 50));
        changePasswordPanelRound.add(newPasswordTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 700, 50));

        changeUsernamePanelRound.add(changePasswordPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        jLabel10.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel10.setText("New Username:");
        changeUsernamePanelRound.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 257, 25));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel2.setText("Password:");
        changeUsernamePanelRound.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 257, 25));

        jLabel9.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel9.setText("Current Username:");
        changeUsernamePanelRound.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 240, 25));

        newUsernameTextField.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        changeUsernamePanelRound.add(newUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 700, 50));

        passwordTextField.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        changeUsernamePanelRound.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 700, 50));

        currentUsernameTextField.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        changeUsernamePanelRound.add(currentUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 700, 50));

        changeButton.setBackground(new java.awt.Color(239, 167, 9));
        changeButton.setBorder(null);
        changeButton.setText("Change ");
        changeButton.setBorderColor(new java.awt.Color(239, 167, 9));
        changeButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        changeButton.setRadius(50);
        changeUsernamePanelRound.add(changeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 300, 50));

        jPanel1.add(changeUsernamePanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 780, 540));

        deleteAccountPanelRound.setRoundBottonLeft(100);
        deleteAccountPanelRound.setRoundBottonRight(100);
        deleteAccountPanelRound.setRoundTopLeft(100);
        deleteAccountPanelRound.setRoundTopRight(100);
        deleteAccountPanelRound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel14.setText("Password:");
        deleteAccountPanelRound.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 240, 25));

        jLabel15.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel15.setText("Confirm Password:");
        deleteAccountPanelRound.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 257, 25));

        deletePasswordTextField.setFont(new java.awt.Font("Mongolian Baiti", 0, 20)); // NOI18N
        deleteAccountPanelRound.add(deletePasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 700, 50));
        deleteAccountPanelRound.add(deleteConfirmPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 700, 50));

        deleteAccountConfirmButton.setBackground(new java.awt.Color(239, 167, 9));
        deleteAccountConfirmButton.setBorder(null);
        deleteAccountConfirmButton.setText("Delete Account");
        deleteAccountConfirmButton.setBorderColor(new java.awt.Color(239, 167, 9));
        deleteAccountConfirmButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        deleteAccountConfirmButton.setRadius(50);
        deleteAccountPanelRound.add(deleteAccountConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 300, 50));

        jPanel1.add(deleteAccountPanelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 780, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 1310, 750));

        jPanel5.setBackground(new java.awt.Color(241, 237, 238));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Account Management");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1310, 90));

        jPanel2.setBackground(new java.awt.Color(227, 143, 11));
        jPanel2.setPreferredSize(new java.awt.Dimension(225, 835));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        jLabel8.setText("Sajilo Serve");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 12, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 52, 210, 1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, 165, 1));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 211, 165, 1));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 275, 165, 1));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 351, 165, 1));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 419, 165, 1));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 491, 165, 1));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 562, 165, 1));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 634, 165, 1));

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 703, 165, 1));

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 778, 165, 1));

        logoutlabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        logoutlabel.setText("Logout");
        logoutlabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 90, 1, 1));
        logoutlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(logoutlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 705, 230, 75));

        homelabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        homelabel.setText("Home");
        homelabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 90, 1, 1));
        homelabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(homelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 140, 250, 70));

        profilelabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        profilelabel.setText("Profile");
        profilelabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 90, 1, 1));
        profilelabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(profilelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 230, 75));

        menulabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        menulabel.setText("Menu");
        menulabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 90, 1, 1));
        menulabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(menulabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 421, 230, 70));

        orderlabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        orderlabel.setText("Orders");
        orderlabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 90, 1, 1));
        orderlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(orderlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 563, 230, 70));

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/home.png"))); // NOI18N
        jPanel2.add(homeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 152, 35, 35));

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/user.png"))); // NOI18N
        profileIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(profileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 290, 35, 35));

        menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/menu.png"))); // NOI18N
        jPanel2.add(menuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 432, 35, 35));

        orderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/check.png"))); // NOI18N
        jPanel2.add(orderIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 575, 35, 35));

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/logout.png"))); // NOI18N
        jPanel2.add(logoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 722, 35, 35));

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/Logo.png"))); // NOI18N
        jPanel2.add(logoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 47, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 230, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeUsernameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAccountManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAccountManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAccountManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAccountManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAccountManagementView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private restaurant.management.system.UIElements.CustomButton changeButton;
    private restaurant.management.system.UIElements.CustomButton changeButton1;
    private restaurant.management.system.UIElements.CustomButton changePasswordButton;
    private restaurant.management.system.UIElements.PanelRound changePasswordPanelRound;
    private restaurant.management.system.UIElements.CustomButton changeUsernameButton;
    private restaurant.management.system.UIElements.PanelRound changeUsernamePanelRound;
    private restaurant.management.system.UIElements.PasswordField confirmNewPasswordTextField;
    private restaurant.management.system.UIElements.PasswordField currentPasswordTextField;
    private restaurant.management.system.UIElements.RoundedTextField currentUsernameTextField;
    private restaurant.management.system.UIElements.CustomButton deleteAccountButton;
    private restaurant.management.system.UIElements.CustomButton deleteAccountConfirmButton;
    private restaurant.management.system.UIElements.PanelRound deleteAccountPanelRound;
    private restaurant.management.system.UIElements.PasswordField deleteConfirmPasswordTextField;
    private restaurant.management.system.UIElements.PasswordField deletePasswordTextField;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel logoutlabel;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JLabel menulabel;
    private restaurant.management.system.UIElements.PasswordField newPasswordTextField2;
    private restaurant.management.system.UIElements.RoundedTextField newUsernameTextField;
    private javax.swing.JLabel orderIcon;
    private javax.swing.JLabel orderlabel;
    private restaurant.management.system.UIElements.PanelRound panelRound1;
    private restaurant.management.system.UIElements.PasswordField passwordTextField;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel profilelabel;
    // End of variables declaration//GEN-END:variables
    
    public void homeNavigation(MouseListener listener){
        homelabel.addMouseListener(listener);
    }
    public JLabel getHomelabel(){
        return homelabel;
    }
    public void profileNavigation(MouseListener listener){
        profilelabel.addMouseListener(listener);
    }
    public JLabel getProfilelabel(){
        return profilelabel;
    }
    public void menuNavigation(MouseListener listener){
        menulabel.addMouseListener(listener);
    }
    public JLabel getMenulabel(){
        return menulabel;
    }
    public void orderNavigation(MouseListener listener){
        orderlabel.addMouseListener(listener);
    }
    public JLabel getOrderlabel(){
        return orderlabel;
    }
    public void logoutNavigation(MouseListener listener){
        logoutlabel.addMouseListener(listener);
    }
    public JLabel getLogoutlabel(){
        return logoutlabel;
    } 
    
    public RoundedTextField getCurrentUsernameTextField() {
        return currentUsernameTextField;
    }

    public PasswordField getPasswordTextField() {
        return passwordTextField;
    }

    public RoundedTextField getNewUsernameTextField() {
        return newUsernameTextField;
    }

    public CustomButton getChangeButton() {
        return changeButton;
    }
    
    public CustomButton getChangeUsernameButton() {
        return changeUsernameButton;
    }
    
    public PasswordField getCurrentPasswordTextField() {
    return currentPasswordTextField; 
}
    public PasswordField getNewPasswordTextField() {
    return newPasswordTextField2;
}
 
    
    public PasswordField getConfirmNewPasswordTextField() {
    return confirmNewPasswordTextField;
}

    // For the password change submit button
    public JButton getChangeButton1() {
        return changeButton1; // assuming this is your button name
    }

    public PanelRound getChangeUsernamePanelRound() {
        return changeUsernamePanelRound;
    }

 
    public void showChangeUsernamePanel() {
        changeUsernamePanelRound.setVisible(true);
    }

    public void hideChangeUsernamePanel() {
        changeUsernamePanelRound.setVisible(false);
    }
    
     public CustomButton getChangePasswordButton() {
        return changePasswordButton;
    }

    public PanelRound getChangePasswordPanelRound() {
        return changePasswordPanelRound;
    }

    // Add methods to show/hide password panel
    public void showChangePasswordPanel() {
        changePasswordPanelRound.setVisible(true);
    }

    public void hideChangePasswordPanel() {
        changePasswordPanelRound.setVisible(false);
    }
    
    public CustomButton getDeleteAccountButton() {
        return deleteAccountButton;
    }
    
    public PanelRound getDeleteAccountPanelRound() {
        return deleteAccountPanelRound;
    }
    
    public PasswordField getDeletePasswordTextField() {
        return deletePasswordTextField;
    }
    
    public PasswordField getDeleteConfirmPasswordTextField() {
        return deleteConfirmPasswordTextField;
    }
    
    public CustomButton getDeleteAccountConfirmButton() {
        return deleteAccountConfirmButton;
    }
    
    public void showDeleteAccountPanel() {
        deleteAccountPanelRound.setVisible(true);
    }
    
    public void hideDeleteAccountPanel() {
        deleteAccountPanelRound.setVisible(false);
    }
}
