/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.Color;

/**
 *
 * @author labis
 */
public class ForgetPasswordView extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPasswordView
     */
    public ForgetPasswordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        roundedTextField1 = new restaurant.management.system.UIElements.RoundedTextField();
        roundedTextField2 = new restaurant.management.system.UIElements.RoundedTextField();
        roundedTextField3 = new restaurant.management.system.UIElements.RoundedTextField();
        roundedTextField4 = new restaurant.management.system.UIElements.RoundedTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 65)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 920, 60));

        nextButton.setBackground(new java.awt.Color(239, 167, 9));
        nextButton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 40)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 740, 150, 50));

        backButton.setBackground(new java.awt.Color(239, 167, 9));
        backButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 750, -1, 40));

        roundedTextField1.setBackground(new java.awt.Color(235, 229, 229));
        roundedTextField1.setText("Confirm Password");
        roundedTextField1.setBorderColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(roundedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 670, 340, 40));

        roundedTextField2.setBackground(new java.awt.Color(235, 229, 229));
        roundedTextField2.setText("Email Address");
        roundedTextField2.setBorderColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(roundedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, 340, 40));

        roundedTextField3.setBackground(new java.awt.Color(235, 229, 229));
        roundedTextField3.setText("Verification Code");
        roundedTextField3.setBorderColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(roundedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 340, 40));

        roundedTextField4.setBackground(new java.awt.Color(235, 229, 229));
        roundedTextField4.setText("New Password");
        roundedTextField4.setBorderColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(roundedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 340, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ;// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPasswordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton nextButton;
    private restaurant.management.system.UIElements.RoundedTextField roundedTextField1;
    private restaurant.management.system.UIElements.RoundedTextField roundedTextField2;
    private restaurant.management.system.UIElements.RoundedTextField roundedTextField3;
    private restaurant.management.system.UIElements.RoundedTextField roundedTextField4;
    // End of variables declaration//GEN-END:variables
}
