/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

/**
 *
 * @author labis
 */
public class ForgetPasswordView extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPasswordView
     */
    public ForgetPasswordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldVerificationCode = new javax.swing.JTextField();
        textFiledEmailAddress = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 130, 390, 40);

        textFieldVerificationCode.setBackground(new java.awt.Color(235, 229, 229));
        textFieldVerificationCode.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        textFieldVerificationCode.setForeground(new java.awt.Color(102, 102, 102));
        textFieldVerificationCode.setText("Verification Code");
        textFieldVerificationCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldVerificationCodeActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldVerificationCode);
        textFieldVerificationCode.setBounds(330, 250, 225, 40);

        textFiledEmailAddress.setBackground(new java.awt.Color(235, 229, 229));
        textFiledEmailAddress.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        textFiledEmailAddress.setForeground(new java.awt.Color(102, 102, 102));
        textFiledEmailAddress.setText("Email Address");
        textFiledEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFiledEmailAddressActionPerformed(evt);
            }
        });
        getContentPane().add(textFiledEmailAddress);
        textFiledEmailAddress.setBounds(330, 200, 225, 30);

        nextButton.setBackground(new java.awt.Color(239, 167, 9));
        nextButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(400, 320, 80, 29);

        backButton.setBackground(new java.awt.Color(239, 167, 9));
        backButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(260, 330, 70, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-3, -4, 650, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldVerificationCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldVerificationCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldVerificationCodeActionPerformed

    private void textFiledEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFiledEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFiledEmailAddressActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new RegisterAsView().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPasswordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField textFieldVerificationCode;
    private javax.swing.JTextField textFiledEmailAddress;
    // End of variables declaration//GEN-END:variables
}
