/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author labis
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        forgetPasswordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signuplabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 390, 40));

        textFieldUsername.setBackground(new java.awt.Color(235, 229, 229));
        textFieldUsername.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        textFieldUsername.setForeground(new java.awt.Color(102, 102, 102));
        textFieldUsername.setText("Username");
        textFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldUsernameFocusLost(evt);
            }
        });
        textFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 225, -1));

        loginButton.setBackground(new java.awt.Color(239, 167, 9));
        loginButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 80, -1));

        forgetPasswordLabel.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        forgetPasswordLabel.setText("Forget Password?");
        getContentPane().add(forgetPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Don't have an Account?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 140, -1));

        signuplabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        signuplabel.setText("SignUp");
        signuplabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuplabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signuplabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signuplabelMouseExited(evt);
            }
        });
        getContentPane().add(signuplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 339, 60, -1));

        passwordField.setBackground(new java.awt.Color(235, 229, 229));
        passwordField.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(102, 102, 102));
        passwordField.setText("Password");
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 225, -1));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsernameActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void textFieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUsernameFocusGained
        // TODO add your handling code here:
        if(textFieldUsername.getText().equals("Username"))
        {
            textFieldUsername.setText("");
            textFieldUsername.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_textFieldUsernameFocusGained

    private void textFieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUsernameFocusLost
        // TODO add your handling code here:
        if(textFieldUsername.getText().equals(""))
        {
            textFieldUsername.setText("Username");
            textFieldUsername.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_textFieldUsernameFocusLost

    private void signuplabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplabelMouseClicked
        // TODO add your handling code here:
        new RegisterAsView().setVisible(true);
    }//GEN-LAST:event_signuplabelMouseClicked

    private void signuplabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplabelMouseEntered
        // TODO add your handling code here:
        signuplabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_signuplabelMouseEntered

    private void signuplabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplabelMouseExited
        // TODO add your handling code here:
        signuplabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_signuplabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel forgetPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel signuplabel;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables
}
