/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.event.ActionListener;

/**
 *
 * @author labis
 */
public class RegistrationOTPView extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationVerificationView
     */
    public RegistrationOTPView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verificationcode = new restaurant.management.system.UIElements.RoundedTextField();
        nextButton = new restaurant.management.system.UIElements.CustomButton();
        backButton = new restaurant.management.system.UIElements.CustomButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 65)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 910, 80));

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 2, 35)); // NOI18N
        jLabel4.setText("Enter the otp sent in your email address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 590, 40));

        verificationcode.setBackground(new java.awt.Color(235, 229, 229));
        verificationcode.setArcHeight(30);
        verificationcode.setArcWidth(30);
        verificationcode.setBorderColor(new java.awt.Color(0, 0, 0));
        verificationcode.setBorderWidth(1);
        verificationcode.setFont(new java.awt.Font("Mongolian Baiti", 0, 36)); // NOI18N
        verificationcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificationcodeActionPerformed(evt);
            }
        });
        getContentPane().add(verificationcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 390, 110));

        nextButton.setBackground(new java.awt.Color(239, 167, 9));
        nextButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nextButton.setText("Next");
        nextButton.setBorderColor(new java.awt.Color(255, 153, 0));
        nextButton.setColor(new java.awt.Color(239, 167, 9));
        nextButton.setColorClick(new java.awt.Color(255, 204, 0));
        nextButton.setColorOver(new java.awt.Color(255, 204, 0));
        nextButton.setFocusable(false);
        nextButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 35)); // NOI18N
        nextButton.setRadius(25);
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 685, 150, 50));

        backButton.setBackground(new java.awt.Color(239, 167, 9));
        backButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backButton.setText("Back");
        backButton.setBorderColor(new java.awt.Color(255, 153, 0));
        backButton.setColor(new java.awt.Color(239, 167, 9));
        backButton.setColorClick(new java.awt.Color(255, 204, 0));
        backButton.setColorOver(new java.awt.Color(255, 204, 0));
        backButton.setFocusable(false);
        backButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 25)); // NOI18N
        backButton.setRadius(25);
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 835));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verificationcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificationcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verificationcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationOTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationOTPView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private restaurant.management.system.UIElements.CustomButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private restaurant.management.system.UIElements.CustomButton nextButton;
    private restaurant.management.system.UIElements.RoundedTextField verificationcode;
    // End of variables declaration//GEN-END:variables

    public void nextNavigation(ActionListener listener){
        nextButton.addActionListener(listener);
    }
    public void backNavigation(ActionListener listener){
        backButton.addActionListener(listener);
    }
    
    public restaurant.management.system.UIElements.RoundedTextField getVerificationcode() {
        return verificationcode;
    }
}
