/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.Color;
import java.awt.event.ActionListener;
import restaurant.management.system.UIElements.PasswordField;

/**
 *
 * @author labis
 */
public class RegisterUsernamePasswordView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterOwnerStaffView2
     */
    public RegisterUsernamePasswordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldUsername = new restaurant.management.system.UIElements.RoundedTextField();
        confirmPasswordField = new restaurant.management.system.UIElements.PasswordField();
        passwordField = new restaurant.management.system.UIElements.PasswordField();
        jLabel1 = new javax.swing.JLabel();
        registerButton = new restaurant.management.system.UIElements.CustomButton();
        backButton = new restaurant.management.system.UIElements.CustomButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldUsername.setBackground(new java.awt.Color(235, 229, 229));
        textFieldUsername.setText("Username");
        textFieldUsername.setBorderColor(new java.awt.Color(0, 0, 0));
        textFieldUsername.setBorderWidth(1);
        textFieldUsername.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 26)); // NOI18N
        getContentPane().add(textFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 410, 45));

        confirmPasswordField.setBackground(new java.awt.Color(235, 229, 229));
        confirmPasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        confirmPasswordField.setBorderColor(new java.awt.Color(0, 0, 0));
        confirmPasswordField.setBorderWidth(1);
        confirmPasswordField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 26)); // NOI18N
        confirmPasswordField.setShowAndHide(true);
        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 590, 410, 45));

        passwordField.setBackground(new java.awt.Color(235, 229, 229));
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        passwordField.setBorderColor(new java.awt.Color(0, 0, 0));
        passwordField.setBorderWidth(1);
        passwordField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 26)); // NOI18N
        passwordField.setShowAndHide(true);
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 410, 45));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 65)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 910, 80));

        registerButton.setBackground(new java.awt.Color(239, 167, 9));
        registerButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        registerButton.setText("Register");
        registerButton.setBorderColor(new java.awt.Color(255, 153, 0));
        registerButton.setColor(new java.awt.Color(239, 167, 9));
        registerButton.setColorClick(new java.awt.Color(255, 204, 0));
        registerButton.setColorOver(new java.awt.Color(255, 204, 0));
        registerButton.setFocusable(false);
        registerButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 38)); // NOI18N
        registerButton.setRadius(30);
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 710, 180, 50));

        backButton.setBackground(new java.awt.Color(239, 167, 9));
        backButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backButton.setText("Back");
        backButton.setBorderColor(new java.awt.Color(255, 153, 0));
        backButton.setColor(new java.awt.Color(239, 167, 9));
        backButton.setColorClick(new java.awt.Color(255, 204, 0));
        backButton.setColorOver(new java.awt.Color(255, 204, 0));
        backButton.setFocusable(false);
        backButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 25)); // NOI18N
        backButton.setRadius(25);
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 730, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1535, 835));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUsernamePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUsernamePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUsernamePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUsernamePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUsernamePasswordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private restaurant.management.system.UIElements.CustomButton backButton;
    private restaurant.management.system.UIElements.PasswordField confirmPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private restaurant.management.system.UIElements.PasswordField passwordField;
    private restaurant.management.system.UIElements.CustomButton registerButton;
    private restaurant.management.system.UIElements.RoundedTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables

    public void backNavigation(ActionListener listener){
        backButton.addActionListener(listener);
    }
    
    public void registerOwner(ActionListener listener){
        registerButton.addActionListener(listener);
    }
    public void registerStaff(ActionListener listener){
        registerButton.addActionListener(listener);
    }
    public void registerCustomer(ActionListener listener){
        registerButton.addActionListener(listener);
    }
    
    public javax.swing.JTextField getUsernameTextField(){
        return textFieldUsername;
    }
    public PasswordField getPasswordField(){
        return passwordField;
    }
    public PasswordField getConfirmPasswordField(){
        return confirmPasswordField;
    }
}
