/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.event.ActionListener;

/**
 *
 * @author acer
 */
public class RegisterStaffView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStaffView
     */
    public RegisterStaffView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textFieldFullName = new restaurant.management.system.UIElements.RoundedTextField();
        textFieldRestaurantName = new restaurant.management.system.UIElements.RoundedTextField();
        textFieldPhoneNumber = new restaurant.management.system.UIElements.RoundedTextField();
        textFieldEmail = new restaurant.management.system.UIElements.RoundedTextField();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldFullName.setText("Full Name");
        textFieldFullName.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        getContentPane().add(textFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 310, 40));

        textFieldRestaurantName.setText("Restaurant Name");
        textFieldRestaurantName.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        getContentPane().add(textFieldRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 310, 40));

        textFieldPhoneNumber.setText("Phone Number");
        textFieldPhoneNumber.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        getContentPane().add(textFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 310, 40));

        textFieldEmail.setText("E-mail");
        textFieldEmail.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        getContentPane().add(textFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 310, 40));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 65)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 910, 80));

        backButton.setBackground(new java.awt.Color(239, 167, 9));
        backButton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 25)); // NOI18N
        backButton.setText("Back");
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 740, 100, 40));

        nextButton.setBackground(new java.awt.Color(239, 167, 9));
        nextButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        nextButton.setText("Next");
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 740, 120, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1535, 835));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStaffView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton nextButton;
    private restaurant.management.system.UIElements.RoundedTextField textFieldEmail;
    private restaurant.management.system.UIElements.RoundedTextField textFieldFullName;
    private restaurant.management.system.UIElements.RoundedTextField textFieldPhoneNumber;
    private restaurant.management.system.UIElements.RoundedTextField textFieldRestaurantName;
    // End of variables declaration//GEN-END:variables
    
    public void registerStaff(ActionListener listener){
        nextButton.addActionListener(listener);
    }
    public void mainpage(ActionListener listener){
        backButton.addActionListener(listener);
    }
    
    public javax.swing.JTextField getFullNameTextField(){
        return textFieldFullName;
    }
    public javax.swing.JTextField getRestaurantNameTextField(){
        return textFieldRestaurantName;
    }
    public javax.swing.JTextField getPhoneNumberTextField(){
        return textFieldPhoneNumber;
    }
    public javax.swing.JTextField getEmailTextField(){
        return textFieldEmail;
    }
}
