/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author labis
 */
public class RegisterOwnerView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterOwnerView
     */
    public RegisterOwnerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldFullName = new javax.swing.JTextField();
        textFieldRestaurantName = new javax.swing.JTextField();
        textFieldPhoneNumber = new javax.swing.JTextField();
        textFieldEmailAddress = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        textFieldEmailAddress1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 65)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 910, 80));

        textFieldFullName.setBackground(new java.awt.Color(239, 235, 235));
        textFieldFullName.setFont(new java.awt.Font("Microsoft JhengHei", 0, 20)); // NOI18N
        textFieldFullName.setForeground(new java.awt.Color(102, 102, 102));
        textFieldFullName.setText("Full Name");
        textFieldFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldFullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldFullNameFocusLost(evt);
            }
        });
        textFieldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFullNameActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 310, -1));

        textFieldRestaurantName.setBackground(new java.awt.Color(239, 235, 235));
        textFieldRestaurantName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        textFieldRestaurantName.setForeground(new java.awt.Color(102, 102, 102));
        textFieldRestaurantName.setText("Restaurant Name");
        textFieldRestaurantName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldRestaurantNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldRestaurantNameFocusLost(evt);
            }
        });
        textFieldRestaurantName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRestaurantNameActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 310, -1));

        textFieldPhoneNumber.setBackground(new java.awt.Color(239, 235, 235));
        textFieldPhoneNumber.setFont(new java.awt.Font("Microsoft JhengHei", 0, 20)); // NOI18N
        textFieldPhoneNumber.setForeground(new java.awt.Color(102, 102, 102));
        textFieldPhoneNumber.setText("Phone Number");
        textFieldPhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldPhoneNumberFocusLost(evt);
            }
        });
        textFieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 310, -1));

        textFieldEmailAddress.setBackground(new java.awt.Color(239, 235, 235));
        textFieldEmailAddress.setFont(new java.awt.Font("Microsoft JhengHei", 0, 20)); // NOI18N
        textFieldEmailAddress.setForeground(new java.awt.Color(102, 102, 102));
        textFieldEmailAddress.setText("Email Address");
        textFieldEmailAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEmailAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldEmailAddressFocusLost(evt);
            }
        });
        textFieldEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailAddressActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 660, 310, -1));

        backButton.setBackground(new java.awt.Color(239, 167, 9));
        backButton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 25)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 745, 100, 30));

        nextButton.setBackground(new java.awt.Color(239, 167, 9));
        nextButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 740, 120, 40));

        textFieldEmailAddress1.setBackground(new java.awt.Color(239, 235, 235));
        textFieldEmailAddress1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 20)); // NOI18N
        textFieldEmailAddress1.setForeground(new java.awt.Color(102, 102, 102));
        textFieldEmailAddress1.setText("Address");
        textFieldEmailAddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEmailAddress1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldEmailAddress1FocusLost(evt);
            }
        });
        textFieldEmailAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailAddress1ActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldEmailAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 590, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFullNameActionPerformed

    private void textFieldRestaurantNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRestaurantNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRestaurantNameActionPerformed

    private void textFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPhoneNumberActionPerformed

    private void textFieldEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailAddressActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new RegisterAsView().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        new RegisterUsernamePasswordView().setVisible(true);
//        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void textFieldEmailAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailAddress1ActionPerformed

    private void textFieldFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFullNameFocusGained
        // TODO add your handling code here:
        if(textFieldFullName.getText().equals("Full Name"))
        {
            textFieldFullName.setText("");
            textFieldFullName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_textFieldFullNameFocusGained

    private void textFieldFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldFullNameFocusLost
        // TODO add your handling code here:
        if(textFieldFullName.getText().equals(""))
        {
            textFieldFullName.setText("Full Name");
            textFieldFullName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_textFieldFullNameFocusLost

    private void textFieldRestaurantNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldRestaurantNameFocusGained
        // TODO add your handling code here:
        if(textFieldRestaurantName.getText().equals("Restaurant Name"))
        {
            textFieldRestaurantName.setText("");
            textFieldRestaurantName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_textFieldRestaurantNameFocusGained

    private void textFieldRestaurantNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldRestaurantNameFocusLost
        // TODO add your handling code here:
        if(textFieldRestaurantName.getText().equals(""))
        {
            textFieldRestaurantName.setText("Restaurant Name");
            textFieldRestaurantName.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_textFieldRestaurantNameFocusLost

    private void textFieldPhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPhoneNumberFocusGained
        // TODO add your handling code here:
        if(textFieldPhoneNumber.getText().equals("Phone Number"))
        {
            textFieldPhoneNumber.setText("");
            textFieldPhoneNumber.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_textFieldPhoneNumberFocusGained

    private void textFieldPhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPhoneNumberFocusLost
        // TODO add your handling code here:]
         if(textFieldPhoneNumber.getText().equals(""))
        {
            textFieldPhoneNumber.setText("Phone Number");
            textFieldPhoneNumber.setForeground(new Color(153,153,153));
        }
       
    }//GEN-LAST:event_textFieldPhoneNumberFocusLost

    private void textFieldEmailAddress1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEmailAddress1FocusGained
        // TODO add your handling code here:
        if(textFieldEmailAddress1.getText().equals("Address"))
        {
            textFieldEmailAddress1.setText("");
            textFieldEmailAddress1.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_textFieldEmailAddress1FocusGained

    private void textFieldEmailAddress1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEmailAddress1FocusLost
        // TODO add your handling code here:
        if(textFieldEmailAddress1.getText().equals(""))
        {
            textFieldEmailAddress1.setText("Address");
            textFieldEmailAddress1.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_textFieldEmailAddress1FocusLost

    private void textFieldEmailAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEmailAddressFocusGained
        // TODO add your handling code here:
        if(textFieldEmailAddress.getText().equals("Email Address"))
        {
            textFieldEmailAddress.setText("");
            textFieldEmailAddress.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_textFieldEmailAddressFocusGained

    private void textFieldEmailAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEmailAddressFocusLost
        // TODO add your handling code here:
        if(textFieldEmailAddress.getText().equals(""))
        {
            textFieldEmailAddress.setText("Email Address");
            textFieldEmailAddress.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_textFieldEmailAddressFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterOwnerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField textFieldEmailAddress;
    private javax.swing.JTextField textFieldEmailAddress1;
    private javax.swing.JTextField textFieldFullName;
    private javax.swing.JTextField textFieldPhoneNumber;
    private javax.swing.JTextField textFieldRestaurantName;
    // End of variables declaration//GEN-END:variables

    public void registerUser(ActionListener listener){
        nextButton.addActionListener(listener);
    }
    
    public javax.swing.JTextField getFullNameTextField(){
        return textFieldFullName;
    }
    public javax.swing.JTextField getRestaurantNameField(){
        return textFieldRestaurantName;
    }
    public javax.swing.JTextField getPhoneField(){
        return textFieldPhoneNumber;
    }
    public javax.swing.JTextField getEmailTextField(){
        return textFieldEmailAddress;
    }
}
