/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.management.system.view;

import java.awt.event.ActionListener;

/**
 *
 * @author labis
 */
public class RegisterOwnerStaffView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterOwnerView
     */
    public RegisterOwnerStaffView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldFullName = new javax.swing.JTextField();
        textFieldRestaurantName = new javax.swing.JTextField();
        textFieldPhoneNumber = new javax.swing.JTextField();
        textFieldEmailAddress = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("Restaurant Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 390, 40));

        textFieldFullName.setBackground(new java.awt.Color(239, 235, 235));
        textFieldFullName.setForeground(new java.awt.Color(102, 102, 102));
        textFieldFullName.setText("Full Name");
        textFieldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFullNameActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 181, 253, -1));

        textFieldRestaurantName.setBackground(new java.awt.Color(239, 235, 235));
        textFieldRestaurantName.setForeground(new java.awt.Color(102, 102, 102));
        textFieldRestaurantName.setText("Restaurant Name");
        textFieldRestaurantName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRestaurantNameActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 215, 253, -1));

        textFieldPhoneNumber.setBackground(new java.awt.Color(239, 235, 235));
        textFieldPhoneNumber.setForeground(new java.awt.Color(102, 102, 102));
        textFieldPhoneNumber.setText("Phone Number");
        textFieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 249, 253, -1));

        textFieldEmailAddress.setBackground(new java.awt.Color(239, 235, 235));
        textFieldEmailAddress.setForeground(new java.awt.Color(102, 102, 102));
        textFieldEmailAddress.setText("Email Address");
        textFieldEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailAddressActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 283, 253, -1));

        backButton.setBackground(new java.awt.Color(239, 167, 9));
        backButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 70, 20));

        nextButton.setBackground(new java.awt.Color(239, 167, 9));
        nextButton.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 317, -1, 23));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePicker/LoginBg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, -1, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFullNameActionPerformed

    private void textFieldRestaurantNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRestaurantNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRestaurantNameActionPerformed

    private void textFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPhoneNumberActionPerformed

    private void textFieldEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailAddressActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new RegisterAsView().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        new RegisterUsernamePasswordView().setVisible(true);
//        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterOwnerStaffView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterOwnerStaffView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField textFieldEmailAddress;
    private javax.swing.JTextField textFieldFullName;
    private javax.swing.JTextField textFieldPhoneNumber;
    private javax.swing.JTextField textFieldRestaurantName;
    // End of variables declaration//GEN-END:variables

    public void registerUser(ActionListener listener){
        nextButton.addActionListener(listener);
    }
    
    public javax.swing.JTextField getFullNameTextField(){
        return textFieldFullName;
    }
    public javax.swing.JTextField getRestaurantNameField(){
        return textFieldRestaurantName;
    }
    public javax.swing.JTextField getPhoneField(){
        return textFieldPhoneNumber;
    }
    public javax.swing.JTextField getEmailTextField(){
        return textFieldEmailAddress;
    }
}
